Add Korean Auto Correst list
libreoffice-kr/autocorr_kr pull request #15
Opened 2020-10-04 12:27 UTC by Ysoeun

금새 > 금세
예) 날이 더워 냉장고에서 꺼낸 얼음이 금세 녹았습니다
몇일 > 며칠
어따 > 얻다
예) 얻다 대고 반말이야
윗층 > 위층
전세집 > 전셋집

안녕하세요~ 
틀린 부분이 있다면 말씀 부탁드립니다~

2020-10-04 12:31 UTC, Ysoeun commented
헐 제가 잘못눌러서 마스터님 브랜치로 바로 날린거 같은데 죄송합니다ㅠㅠㅠ

2020-10-05 12:37 UTC, studioego requested changes
`금새`와 `어따`부분만 삭제하고 다시 RP전달해주시면 병합(머지,merge)하겠습니다

2020-10-05 12:37 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="금새" block-list:name="금세"/>
국립국어원의 표준국어대사전과 우리말샘에서 `금새`라는 낱말이 있습니다
그래서 이 부분은 삭제해야할 것 같습니다 
참고 `금새`
https://ko.dict.naver.com/#/entry/koko/e471eb9cfdc147d2a866158542ef9c7b

2020-10-05 12:37 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="어따" block-list:name="얻다"/>
국립국어원의 표준국어대사전과 우리말샘에서 `어따`가 정의되어 있습니다. 그래서 이 부분은 삭제 해야할것 같습니다
`어따`: ` 무엇이 몹시 심하거나 하여 못마땅해서 빈정거릴 때 내는 소리. `

참고: `어따`
https://ko.dict.naver.com/#/entry/koko/e134b2130ad3456ea5f4b1c7912b6328

2020-10-05 12:38 UTC, studioego commented
> 헐 제가 잘못눌러서 마스터님 브랜치로 바로 날린거 같은데 죄송합니다ㅠㅠㅠ

괜찮습니다. 이렇게 해보면서 체험하는것이죠 :+1:

2020-10-05 16:29 UTC, Ysoeun commented
금새
어따

알려주신 부분 삭제했습니다!
번거롭게 해드려서 정말 죄송해요 ㅠㅠ
프로젝트 열어주셔서 감사합니다❤

2020-10-05 17:56 UTC, merged

2020-10-05 17:57 UTC, studioego commented
LTGM. I've just merged it. Thanks!

2020-10-05 17:58 UTC, studioego commented
> 금새
> 
> 어따
> 
> 
> 
> 알려주신 부분 삭제했습니다!
> 
> 번거롭게 해드려서 정말 죄송해요 ㅠㅠ
> 
> 프로젝트 열어주셔서 감사합니다❤

병합(머지/merge)완료했습니다. 즐거운 핵토버페스트 기간 되시길 😀