Add : Korean Autocorr List
libreoffice-kr/autocorr_kr pull request #20
Opened 2020-10-06 04:37 UTC by realapril

귀뜸>귀띰
마춰>맞춰
두건 추가합니다

2020-10-06 06:19 UTC, studioego commented
LGTM. I'll merge it
병합(머지/merge) 합니다.

2020-10-06 06:23 UTC, studioego requested changes
`귀딤`을 `귀띰`으로 수정하여 제출 부탁드립니다.

2020-10-06 06:23 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="귀뜸" block-list:name="귀딤"/>
`귀뜸`->`귀띰` 이라고 하셨는데, 
`귀딤`이라고 작성하셔서 수정해야할것 같습니다 
국립국어원 표준국어대사전 `귀띰`
https://ko.dict.naver.com/#/entry/koko/b3834d134ef148fba8d6de11699c5c03

2020-10-06 06:24 UTC, studioego commented
리뷰해보니 `귀띰`으로 수정이 필요함을 확인하였습니다. 수정하여 제출하시면 병합(머지/merge)하겠습니다.

2020-10-07 04:32 UTC, realapril commented
오타를 수정하였습니다. 감사합니다!

2020-10-08 13:16 UTC, studioego approved these changes
LGTM. I'll merge it!

2020-10-08 13:16 UTC, merged