Update DocumentList.xml
libreoffice-kr/autocorr_kr pull request #23
Opened 2020-10-06 07:40 UTC by waltzbucks

추가: 배개, 베게, 벼게 -> 베개

2020-10-06 16:09 UTC, studioego requested changes
고려대 한국어대사전에서는 `베게`라는 낱말이 수록되어 있습니다.

사전의 뜻이 있다보니 이 부분은 삭제해야할 것 같습니다
참고 `베게`
https://ko.dict.naver.com/#/entry/koko/29991d14d9b34cd0902fbf261fed0607

수정해서 제출해주시면 PR수락후  병합하겠습니다

2020-10-06 16:09 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="베게" block-list:name="베개"/>
고려대 한국어대사전에서는 `베게`라는 낱말이 수록되어 있습니다.

사전의 뜻이 있다보니 이 부분은 삭제해야할 것 같습니다
참고 `베게`
https://ko.dict.naver.com/#/entry/koko/29991d14d9b34cd0902fbf261fed0607

2020-10-06 21:30 UTC, waltzbucks commented
고려대한국어대사전에는 있으나 방언이라고 되어있는데
자동교정은 표준어로 교정 해주는게 좋지 않을 까요?

2020-10-07 00:00 UTC, waltzbucks commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="베게" block-list:name="베개"/>
`베게` 는 고려대 한국어대사전에서 찾아볼 수 있지만, 방언이라고 되어 있습니다.
자동교정시에는 표준어 `베개`를 사용 하는게 좋을 것 같다고 생각 됩니다.

2020-10-08 13:47 UTC, studioego requested changes
수정 해주시기 바랍니다

2020-10-08 13:47 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="베게" block-list:name="베개"/>
사투리도 우리말입니다. 만약에 국어 선생님이 사투리 관련 소재 수업을 위해서 글을 작성하거나 소설가가 
사투리 관련으로 글을 쓰다보면 버그라고 알릴 수 있을 것 같습니다.

그리고 속담에 `베게`라는 단어가 있다보니 수정을 해야할것 같습니다
`갯고랑을 베게 되었다`
- 갯고랑을 베개 삼아 비참하게 한데에서 죽을 지경에 이르렀다는 뜻으로, 욕으로 쓰는 말
https://dic.daum.net/word/view.do?wordid=kkw000008625&q=%EA%B0%AF%EA%B3%A0%EB%9E%91%EC%9D%84+%EB%B2%A0%EA%B2%8C+%EB%90%98%EC%97%88%EB%8B%A4&suptype=OPENDIC_KK

국어사전 시초 '말모이·조선말 큰사전 원고' 보물 된다
https://www.newsis.com/view/?id=NISX20201008_0001191943&cID=10701&pID=10700

2020-10-08 13:47 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="베게" block-list:name="베개"/>
해당 부분만 삭제하고 병합(머지/merge)를 할까 하는데 동의하시면 병합하겠습니다.

2020-10-08 15:24 UTC, waltzbucks commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="베게" block-list:name="베개"/>
네 이해 했습니다.  해당 `베게` 라인 제거 합니다.

2020-10-08 15:29 UTC, waltzbucks reviewed
Delete `<block-list:block block-list:abbreviated-name="베게" block-list:name="베개"/>`

2020-10-08 16:04 UTC, studioego approved these changes
LGTM. I'll merge it!

2020-10-08 16:04 UTC, merged

2020-10-08 16:04 UTC, studioego commented
병합(머지/merge) 완료하였습니다. 감사합니다!