Add Korean Auto Correct list
libreoffice-kr/autocorr_kr pull request #27
Opened 2020-10-06 19:51 UTC by constmoon

궂이 -> 굳이
구지 -> 굳이
됫 -> 됐

이렇게 추가했습니다.

2020-10-08 13:26 UTC, studioego requested changes
`구지`와 `됫`
2개의 낱말에 대해서 삭제 부탁드립니다.

2020-10-08 13:26 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="구지" block-list:name="굳이"/>
`구지`에 대한 낱말이 있기때문에 해당 부분 삭제 부탁드립니다

`구지 (久持)` 
[명사] [한의 ] 맥을 좀 오래 짚어 보는 일. 일반적으로 맥은 1분 정도 보는데 3~5분 정도 보는 것을 이른다.
https://ko.dict.naver.com/#/entry/koko/cdfeef1bd979470399669beb585268f6

`구지 (九地)`
[명사]
1. 땅의 가장 낮은 곳.
2. 적에게 쉽게 발견되지 않을 만큼 깊숙이 팬 땅.
3. 손자 병법에서, 싸우기에 이롭고 불리한 데에 따라 구별한 아홉 가지 땅. 이에는 산지(散地), 경지(輕地), 쟁지(...
https://ko.dict.naver.com/#/entry/koko/dbaefa2ef8cf44e8ab9c103efa87e4f9

`구지 (俱胝)`
[명사] [불교 ] 인도에서 쓰는 큰 수의 하나. 일천만을 뜻한다.
https://ko.dict.naver.com/#/entry/koko/3696bc0e6e964f65a3f0fd957c446494

`구지 (矩地)`
[명사] 옛날에 땅이 네모진 것이라 생각한 데서, ‘대지’를 이르는 말.
https://ko.dict.naver.com/#/entry/koko/40f5653f26344e979d0d58df81f2db68

`구지 (溝池)` 
1. 명사 도랑과 못을 아울러 이르는 말.
2. 명사 역사 적이 침입하지 못하도록 성(城) 둘레에 파 놓은 못.
https://ko.dict.naver.com/#/entry/koko/645e4cbf64ef4e2c8a6f5c94db581d8e

2020-10-08 13:26 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="됫" block-list:name="됐"/>
한글자만 임력하면 `됫` 하나만 글을 썼을때 `됏`으로 자동으로 바뀌는 이슈가 있습니다
그래서 해당 부분 삭제 부탁드립니다.

2020-10-10 04:04 UTC, constmoon commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="됫" block-list:name="됐"/>
@studioego '됏'도 잘못된 표기법 아닌가요? 됏이 한 번 더 '됐'이 되어야하는 게 아닌지 궁금합니다.

2020-10-10 04:48 UTC, constmoon commented
- '됫' 삭제
- '구지' 삭제
- '되요' -> '됐요' 케이스를 '돼요'로 변경

위와 같이 수정했습니다.
@studioego

2020-10-10 16:18 UTC, studioego approved these changes
LGTM. I'll merge it!

2020-10-10 16:19 UTC, merged

2020-10-10 16:19 UTC, studioego commented
병합(머지/merge)완료하였습니다. 감사합니다.