Add Korean Auto Correct list
libreoffice-kr/autocorr_kr pull request #43
Opened 2020-10-16 01:23 UTC by chikeem90

괴변 -> 궤변
축척 -> 축적
추스리다 -> 추스르다
초죽음 -> 초주검
챗바퀴 -> 쳇바퀴

2020-10-19 14:04 UTC, studioego requested changes

2020-10-19 14:04 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="괴변" block-list:name="궤변"/>
`괴변`
표준국어대사전에서는 괴변에 대해 2가지 뜻이 있습니다
`괴변 1 怪變` [궤ː변/괴ː변]
명사 예상하지 못한 괴상한 재난이나 사고.
`괴변 2 壞變` [궤ː변/괴ː변]
 명사 무너져 모양이 바뀜.

이미 사전에 등록된 낱말이 있으므로 삭제를 해야할 것 같습니다.

2020-10-19 14:04 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="축척" block-list:name="축적"/>
`축척`
표준국어대사전에서는 `축척`에 대해 4가지 뜻이 있습니다
`축척 3 縮尺` [축척]
 1.  명사 지도에서의 거리와 지표에서의 실제 거리와의 비율. 몇천분의 일, 몇만분의 일 따위로 표시한다.
 2.  명사 피륙 따위가 일정한 자수에 차지 아니함.
`축척 1 逐斥` -  명사 쫓아서 물리침.
`축척 4 蹙蹐` -  명사 종종걸음으로 살살 걸음.
`축척 2 踧踖` - 조심하여 걸음. 

이미 사전에 등록된 낱말이 있으므로 삭제를 해야 할 것 같습니다.

2020-10-19 14:04 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="추스리다" block-list:name="추스르다"/>
`추스리다`
국립국어원 우리말샘에서는 `추스르다’의 방언 (경남) `으로 등록되어 있습니다.
혹시, 방언관련으로 사전 만드는 분이 작업하다 이부분 자동 교정하면 난감할 수 있습니다. 
https://ko.dict.naver.com/#/entry/koko/3849ce4b6d27476a820f6928f354af1f

2020-10-19 14:06 UTC, studioego requested changes
`괴변`, `축척`, `추스리다` 3개만 삭제하시고, PR전달하실때, 고쳐야 할 낱말의 가나다 오름차순으로 추가해주시기 바랍니다.

2020-10-21 08:40 UTC, chikeem90 commented
변경해서 다시 커밋하였습니다.
다음 추가시 잘 확인하고 추가해야겠네요.

2020-10-22 02:20 UTC, studioego approved these changes
LGTM. I'll merge it!

2020-10-22 02:20 UTC, studioego commented
검토(리뷰/review)하였고, 해당 변경 사항을 병합(머지/merge)합니다.
감사합니다.

2020-10-22 02:20 UTC, merged