Add Korean Auto Correct list
libreoffice-kr/autocorr_kr pull request #47
Opened 2020-10-18 07:03 UTC by lucas-jg

#5 
봽겠습니다 -> 뵙겠습니다.
뵈요 -> 봬요
이뿌게 -> 이쁘게
임마 -> 인마

2020-10-19 14:14 UTC, studioego requested changes
`뵈요`, `이뿌게`, `임마`에 대해서 삭제 및 수정 완료하면 병합하겠습니다.

2020-10-19 14:14 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="이뿌게" block-list:name="이쁘게"/>
`이뿌게`의  표준말은 `예쁘게`입니다.
https://ko.dict.naver.com/#/entry/koko/61a8e24d442d4b47a7a241797f968195

수정 요청합니다.

2020-10-19 14:14 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="임마" block-list:name="인마"/>
`임마` - '이마'의 방언(충청, 중국 길림성)
https://ko.dict.naver.com/#/entry/koko/dc90eb43c50742089d2559d76be71527


사투리말이므로 자동 교정하긴 부적합합니다. 그래서 삭제 요청합니다

2020-10-19 14:14 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="뵈요" block-list:name="봬요"/>
`뵈요`에 대해서 표준국어대사전과 우리말샘에서 
`뵈다` 1 [붸ː다/뵈ː다] ( 활용형: `뵈요` ) -  동사 ‘보이다’의 준말.
`뵈다` 2 [붸ː다/뵈ː다] ( 활용형: `뵈요` ) -  동사 웃어른을 대하여 보다.
`뵈다` 3 [붸ː다/뵈ː다] ( 활용형: `뵈요` ) -  동사 ‘보이다’의 준말.
`뵈다` ( 활용형: `뵈요` ) -   형용사 옛말 ‘배다’의 옛말.


이미 `뵈요`라는 활용형이 사전이 등록되어 있으므로 삭제 부탁드립니다.

2020-10-20 04:13 UTC, lucas-jg commented
수정사항에 대해 적용하였습니다.

2020-10-20 05:15 UTC, studioego approved these changes
LGTM. I'll merge it

2020-10-20 05:15 UTC, merged

2020-10-20 05:15 UTC, studioego commented
검토(리뷰/review)하였고, 이상 없어서 병합(머지/merge)하였습니다. 감사합니다!