Add Korean Auto Correct list
libreoffice-kr/autocorr_kr pull request #52
Opened 2020-10-28 05:21 UTC by jil8885

헷갈리기 쉬운 단어 3가지를 추가하였습니다.

* 바껴서 > 바꿔서
* 헥갈리다 > 헷갈리다
* 삐지다 > 삐치다

2020-10-29 14:47 UTC, studioego requested changes
수정 요청한 내용 적용 부탁드립니다. 완료되면 병합(머지/merge)하겠습니다.

2020-10-29 14:47 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="바껴서" block-list:name="바꿔서"/>
국립국어원 우리말샘에 `바끼다`가 수록되어 있습니다
https://ko.dict.naver.com/#/entry/koko/93c3ce0dedf945c885c1ba1a07c6d77a
방언] ‘바뀌다’의 방언 (경기, 경상, 전라, 충청) 
이 낱말의 활용형: `바껴서`라 정의가 되어있습니다. 해당 부분 삭제 부탁드립니다

2020-10-29 14:47 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="삐지다" block-list:name="삐치다"/>
`삐지다`
국립국어원 표준국어대사전에서 `칼 따위로 물건을 얇고 비스듬하게 잘라 내다.`로 정의되어 있습니다. 
https://ko.dict.naver.com/#/entry/koko/eee1b0cd22974d0da1f392e9b3c1cdde
그리고
` 성나거나 못마땅해서 마음이 토라지다. ` 라는 뜻도 있습니다
https://ko.dict.naver.com/#/entry/koko/3f6f89d49afe4d1594468082fae89861

그래서 해당 내용 삭제 부탁드립니다

2020-10-29 23:51 UTC, jil8885 commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="삐지다" block-list:name="삐치다"/>
말씀하신 대로 두가지 단어를 수정해두었습니다.

2020-10-30 05:12 UTC, studioego approved these changes
LGTM. I'll merge it. 검토(리뷰/review)확인하였습니다. 승인합니다

2020-10-30 05:13 UTC, studioego commented
검토(리뷰/review)결과 이상 없어서 병합(머지/merge)합니다.

2020-10-30 05:13 UTC, merged