Add Korean Auto Correct list
libreoffice-kr/autocorr_kr pull request #99
Opened 2022-10-16 08:29 UTC by yeslee-v

Add Korean Auto Correct list

받아드리다 -> 받아들이다
새우다 -> 세우다
폐혜 -> 폐해

2022-10-26 09:04 UTC, studioego commented
나머지 부분에 대해서는 문제 없는데 `새우다`는 삭제하면 merge하겠습니다.

2022-10-26 09:05 UTC, studioego requested changes

2022-10-26 09:05 UTC, studioego commented on DocumentList.xml
> +  <block-list:block block-list:abbreviated-name="새우다" block-list:name="세우다"/>
이미 `새우다`에 대한 낱말이 있어서 해당 부분 삭제 부탁드립니다.

참고 새우다1 https://ko.dict.naver.com/#/entry/koko/88104e941f0a489d89cfdc887cadbfdc

2022-10-26 10:47 UTC, yeslee-v commented
리뷰 감사드리며 말씀 주신 부분 반영하였습니다😃

2022-10-26 15:07 UTC, studioego approved these changes
LGTM. Merge it. 
코로나로 인해 이제야 확인한점 죄송합니다.

2022-10-26 15:08 UTC, merged

2022-10-27 04:27 UTC, yeslee-v commented
@studioego 얼른 쾌차하시길 바라겠습니다🙏
시간되실 때 hacktoberfest 라벨도 붙여주시면 감사하겠습니다.

2022-10-27 04:34 UTC, studioego commented
추가 완료하였습니다